INFO:Slither:Compilation warnings/errors on /sb/0x17aa210b34e776d93ecbf75ce379dffb90930efd.sol:
Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> /sb/0x17aa210b34e776d93ecbf75ce379dffb90930efd.sol:290:9:
    |
290 |         uint _maxIterations,
    |         ^^^^^^^^^^^^^^^^^^^


ERROR:root:Error in /sb/0x17aa210b34e776d93ecbf75ce379dffb90930efd.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/__main__.py", line 564, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/__main__.py", line 53, in process
    triage_mode=args.triage_mode)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/slither.py", line 58, in __init__
    self._analyze_contracts()
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 249, in _analyze_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 311, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 357, in _analyze_struct_events
    contract.analyze_events()
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/declarations/contract.py", line 419, in analyze_events
    event.analyze(self)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/declarations/event.py", line 38, in analyze
    elem = EventVariableSolc(elem_to_parse)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/variables/variable_declaration.py", line 52, in __init__
    self._init_from_declaration(var, var['value'])
KeyError: 'value'

